name: pr-completed

on:
  workflow_run:
    workflows:
      - pr
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      pull-requests: write
    steps:
      - name: Download pr-comment-body.txt
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          run-id: ${{ github.event.workflow_run.id }}
          name: pr-comment-body.txt
      - name: Create pr-comment.txt
        run: |
          set -eu

          (
            cat << EOF
          <!-- pr-comment -->
          Results for [build job](https://github.com/${{github.repository}}/actions/runs/${{github.event.workflow_run.id}}) (at ${{ github.event.workflow_run.head_sha }}):

          EOF

            if [ -f pr-comment-body.txt ]; then
              cat pr-comment-body.txt
            else
              echo '(No pr-comment-body.txt artifact found from this job.)'
            fi
          ) > pr-comment.txt
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          comment-author: 'github-actions[bot]'
          body-includes: |
            <!-- pr-comment -->
      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body-path: pr-comment.txt
